# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35700f9a9a3e84cdeae40e3f836a9e05f9c28a67925861e4243d64267efb5a425be3c3d4bffaaeb842ae9f2d45d83ff4d0d215494aa2d948c0309448b1aee59f

test:
  secret_key_base: fa4f6bc64607757d18e2ba9b48572db273df4a73db7adbf8eb6beb0f1cfa9bcc1f254e7bedf420a020c50a902dd3fa9b8911eb987df6677303688e89ea8cf978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
